// const abi = /* abi generated by the compiler */
// const ZombieFeedingContract = web3.eth.contract(abi)
// const contractAddress = /* our contract address on Ethereum after deploying */
// const ZombieFeeding = ZombieFeedingContract.at(contractAddress)

// // Assuming we have our zombie's ID and the kitty ID we want to attack
// let zombieId = 1;
// let kittyId = 1;

// let apiUrl = "https://api.cryptokitties.co/kitties/" + kittyId
// $.get(apiUrl, function(data) {
//   let imgUrl = data.image_url
//   // do something to display the image
// })

// // When the user clicks on a kitty:
// $(".kittyImage").click(function(e) {
//   // Call our contract's `feedOnKitty` method
//   ZombieFeeding.feedOnKitty(zombieId, kittyId)
// })

// // Listen for a NewZombie event from our contract so we can display it:
// ZombieFactory.NewZombie(function(error, result) {
//   if (error) return
//   // This function will display the zombie, like in lesson 1:
//   generateZombie(result.zombieId, result.name, result.dna)
// })